name: Deploy VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: deploy to vps ndbdesign
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.vps_ndbdesign_sshkey }}
          REMOTE_HOST: ${{ secrets.vps_ndbdesign_host }}
          REMOTE_USER: ${{ secrets.vps_ndbdesign_login }}
          SOURCE: "www/wp-content/themes/ndbdesign"
          TARGET: "/var/www/wordpress/wp-content/themes/ndbdesign"
