name: Deploy VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout ndbdesign
        uses: actions/checkout@v2
      - name: deploy to vps ndbdesign
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_NDBDESIGN_SSHKEY }}
          REMOTE_HOST: ${{ secrets.VPS_NDBDESIGN_HOST }}
          REMOTE_USER: ${{ secrets.VPS_NDBDESIGN_LOGIN }}
          SOURCE: "www/wp-content/themes/ndbdesign"
          TARGET: "/var/www/wordpress/wp-content/themes"
